print('Thirty', 'Days', 'Of', 'Python')
print('Coding', 'For', 'All')

company = 'coding For All'
print(company)
print(len(company))
print(company.upper())
print(company.lower())
print(company.capitalize())
print(company.title())
print(company.swapcase())
print(company.split()[0])
print('coding' in company)
print(company.index('coding'))
print(company.find('coding'))
print(company.replace('coding', 'Python'))
print('Python for Everyone'.replace('Everyone', 'All'))
print(company.split(' '))
print('Facebook,Google,Microsoft,Apple,IBM,Oracle,Amazon'.split(','))
print(company[0])
print(len(company)-1)
print(company[10])
a,b,c = "Python For Everyone".split(' ')
print(a[0]+b[0]+c[0])
print(company.index('c'))
print(company.index('F'))
print(company.rfind('l'))
print('You cannot end a sentence with because because because is a conjunction'.find('because'))
print('You cannot end a sentence with because because because is a conjunction'.rfind('because'))
print('You cannot end a sentence with because because because is a conjunction'[31:54])
print(company.startswith('coding'))
print(company.startswith('Coding'))
print(' Coding For All  '.strip(' '))
libraries = ['Django', 'Flask', 'Bottle', 'Pyramid', 'Falcon']
print('# '.join(libraries))
print('I am enjoying this challenge.\nI just wonder what is next.')
print('Name\tAge\tCoutry\tCity\nManish\t21\tIndia\tMotihari')

a = 8
b = 6
print(f'{a} + {b} = {a + b}')
print(f'{a} - {b} = {a - b}')
print(f'{a} * {b} = {a * b}')
print(f'{a} / {b} = {a / b:.2f}')
print(f'{a} % {b} = {a % b}')
print(f'{a} // {b} = {a // b}')
print(f'{a} ** {b} = {a ** b}')